### ISSUE TITLE
~ is not interpreted as $HOME

### ISSUE THREAD

**Issue by brainstorm** [EugenMayer/go-antibash-boilerplate#3]
Thanks for this handy wrapper!

When I run your API with 

```
sshAPI, err := sshwrapper.DefaultSshApiSetup("myhost", 22, "user", "/Users/user/.ssh/id_ed25519")
```

Works as expected. Unfortunately this does not work:

```
sshAPI, err := sshwrapper.DefaultSshApiSetup("myhost", 22, "user", "~/.ssh/id_ed25519")
```

And leads to file not found and segfault:

```
open ~/.ssh/id_ed25519: no such file or directorypanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x152e7c7]

goroutine 1 [running]:
github.com/eugenmayer/go-sshclient/sshwrapper.(*SshApi).Connect(0xc00019e0c0, 0xc00019c100, 0x0, 0xc000131bf0)
        /Users/user/go/src/github.com/eugenmayer/go-sshclient/sshwrapper/client.go:62 +0x117
github.com/eugenmayer/go-sshclient/sshwrapper.(*SshApi).ConnectAndSession(0xc00019e0c0, 0xc00010c240, 0x31)
        /Users/user/go/src/github.com/eugenmayer/go-sshclient/sshwrapper/client.go:14 +0x2f
github.com/eugenmayer/go-sshclient/sshwrapper.(*SshApi).Run(0xc00019e0c0, 0x164222a, 0x2, 0x1, 0x1, 0x31, 0x0, 0x0, 0x17956a0)
        /Users/user/go/src/github.com/eugenmayer/go-sshclient/sshwrapper/client.go:91 +0x236
github.com/umccr/cli/cmd.sshHpc(0x164222a, 0x2)
        /Users/user/go/src/github.com/umccr/cli/cmd/hpc.go:89 +0x119
github.com/umccr/cli/cmd.glob..func2(0x1b7f420, 0x1ba4908, 0x0, 0x0)
        /Users/user/go/src/github.com/umccr/cli/cmd/hpc.go:31 +0x36
github.com/spf13/cobra.(*Command).execute(0x1b7f420, 0x1ba4908, 0x0, 0x0, 0x1b7f420, 0x1ba4908)
        /Users/user/go/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x1b7f680, 0x1, 0x16420af, 0x1)
        /Users/user/go/src/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/user/go/src/github.com/spf13/cobra/command.go:800
github.com/umccr/cli/cmd.Execute()
        /Users/user/go/src/github.com/umccr/cli/cmd/root.go:36 +0x32
main.main()
        /Users/user/go/src/github.com/umccr/cli/main.go:20 +0x20
```

IMHO it would be super handy to combine your lib with something like this:

https://github.com/kevinburke/ssh_config

Cheers!

**Comment by brainstorm** [comment]
Sorry, wrong repo, I was meaning to file it under https://github.com/EugenMayer/go-sshclient, not here, tab confusion :/

**Comment by EugenMayer** [comment]
This is right, because there is no magic string expansion for `~` in go - it is just string.

You can use a tool like

```go
func ExpandTildeInPath(path string) string {
	usr, _ := user.Current()
	home := usr.HomeDir
	if path == "~" {
		// In case of "~", which won't be caught by the "else if"
		path = home
	} else if strings.HasPrefix(path, "~/") {
		// Use strings.HasPrefix so we don't match paths like
		// "/something/~/something/"
		path = filepath.Join(home, path[2:])
	}

	return path
}
```

e..g you find it in https://github.com/EugenMayer/go-exec/blob/master/runner/command.go#L13

**Comment by EugenMayer** [comment]
I did adjust the README and removed the ~ usage to avoid the confusion / expectation it is automagically expaneded - thank you for the hint

**Comment by brainstorm** [comment]
Good snippet! I just went for:

```Go
import "github.com/mitchellh/go-homedir"
home, err := homedir.Dir()
```

Then simple string interpolation:

```
home+"/.ssh/id_ed25519"
```

Next would be determining host/pubkey semi-automatically (with some security guarantees as you commented in another issue).
